// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW1PD1BGNKvT8ND5LLeV4E-XvalrQ3xvY',
    appId: '1:543587642988:web:42801345f6474e1f23b249',
    messagingSenderId: '543587642988',
    projectId: 'wechat-ba238',
    authDomain: 'wechat-ba238.firebaseapp.com',
    storageBucket: 'wechat-ba238.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHZ4LvK_INLZfeHUnemOs3msSkb9PBQHs',
    appId: '1:543587642988:android:502d7545d46b2dec23b249',
    messagingSenderId: '543587642988',
    projectId: 'wechat-ba238',
    storageBucket: 'wechat-ba238.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKeRe5ewet1uw5DNAUG2dFS01PClYONIU',
    appId: '1:543587642988:ios:de7ba2509d61563123b249',
    messagingSenderId: '543587642988',
    projectId: 'wechat-ba238',
    storageBucket: 'wechat-ba238.appspot.com',
    androidClientId: '543587642988-ob2sqeqpccima3hq4nsqht7vjfoscptg.apps.googleusercontent.com',
    iosClientId: '543587642988-gbf182gavsqdlp12lnkb5obk44s38et1.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKeRe5ewet1uw5DNAUG2dFS01PClYONIU',
    appId: '1:543587642988:ios:346bed3ad1da8fc723b249',
    messagingSenderId: '543587642988',
    projectId: 'wechat-ba238',
    storageBucket: 'wechat-ba238.appspot.com',
    androidClientId: '543587642988-ob2sqeqpccima3hq4nsqht7vjfoscptg.apps.googleusercontent.com',
    iosClientId: '543587642988-jq91gds64alpko0mlov8u6pv7eghg96q.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat.RunnerTests',
  );
}
